HOMEWORK4 , Done
T1000-Swift-Madina/HW-WEEK1-DAY4-CONDITIONALS-AND-LOOPS pull request #6
Opened 2021-09-30 00:27 UTC by AfafSaleh55

2021-10-03 17:48 UTC, SalimNoor reviewed
Try to improve the same code using better options we discussed like using loops / in-built functions / dictionaries

2021-10-05 06:42 UTC, azfay3 requested changes
Remove spaces

2021-10-05 06:42 UTC, azfay3 commented on Homework4/HomeWork4:1.playground/Contents.swift
> +var Cities = "Mahkh"
No spaces!

2021-10-05 06:42 UTC, azfay3 commented on Homework4/HomeWork4:1.playground/Contents.swift
> +citiy.append(" Mahkh ")
It is different than this!

2021-10-05 07:41 UTC, azfay3 commented
Great job!

2021-10-05 07:41 UTC, closed without merging